
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */

#include "board/irq.h"
#include "board/pgm.h"
#include "command.h"
#include "compiler.h"
#include "initial_pins.h"

void
ctr_run_initfuncs(void)
{
    extern void alloc_init(void);
    alloc_init();
    extern void initial_pins_setup(void);
    initial_pins_setup();
    extern void watchdog_init(void);
    watchdog_init();
    extern void timer_init(void);
    timer_init();
    extern void can_init(void);
    can_init();
    extern void chipid_init(void);
    chipid_init();
}

void
ctr_run_shutdownfuncs(void)
{
    extern void sendf_shutdown(void);
    sendf_shutdown();
    extern void move_reset(void);
    move_reset();
    extern void digital_out_shutdown(void);
    digital_out_shutdown();
    extern void stepper_shutdown(void);
    stepper_shutdown();
    extern void trsync_shutdown(void);
    trsync_shutdown();
    extern void analog_in_shutdown(void);
    analog_in_shutdown();
    extern void spidev_shutdown(void);
    spidev_shutdown();
    extern void pwm_shutdown(void);
    pwm_shutdown();
    extern void tmcuart_shutdown(void);
    tmcuart_shutdown();
    extern void st7920_shutdown(void);
    st7920_shutdown();
    extern void hd44780_shutdown(void);
    hd44780_shutdown();
    extern void clear_active_irq(void);
    clear_active_irq();
    extern void timer_reset(void);
    timer_reset();
    extern void canserial_shutdown(void);
    canserial_shutdown();
}

void
ctr_run_taskfuncs(void)
{
    irq_poll();
    extern void trsync_task(void);
    trsync_task();
    irq_poll();
    extern void analog_in_task(void);
    analog_in_task();
    irq_poll();
    extern void buttons_task(void);
    buttons_task();
    irq_poll();
    extern void tmcuart_task(void);
    tmcuart_task();
    irq_poll();
    extern void counter_task(void);
    counter_task();
    irq_poll();
    extern void thermocouple_task(void);
    thermocouple_task();
    irq_poll();
    extern void adxl345_task(void);
    adxl345_task();
    irq_poll();
    extern void spi_angle_task(void);
    spi_angle_task();
    irq_poll();
    extern void mpu9250_task(void);
    mpu9250_task();
    irq_poll();
    extern void lis2dw_task(void);
    lis2dw_task();
    irq_poll();
    extern void ldc1612_task(void);
    ldc1612_task();
    irq_poll();
    extern void hx71x_capture_task(void);
    hx71x_capture_task();
    irq_poll();
    extern void ads1220_capture_task(void);
    ads1220_capture_task();
    irq_poll();
    extern void watchdog_reset(void);
    watchdog_reset();
    irq_poll();
    extern void timer_task(void);
    timer_task();
    irq_poll();
    extern void canserial_rx_task(void);
    canserial_rx_task();
    irq_poll();
    extern void canserial_tx_task(void);
    canserial_tx_task();
    irq_poll();
}

uint8_t __always_inline
ctr_lookup_static_string(const char *str)
{
    if (__builtin_strcmp(str, "Shutdown cleared when not shutdown") == 0)
        return 2;
    if (__builtin_strcmp(str, "Timer too close") == 0)
        return 3;
    if (__builtin_strcmp(str, "sentinel timer called") == 0)
        return 4;
    if (__builtin_strcmp(str, "Invalid command") == 0)
        return 5;
    if (__builtin_strcmp(str, "Message encode error") == 0)
        return 6;
    if (__builtin_strcmp(str, "Command parser error") == 0)
        return 7;
    if (__builtin_strcmp(str, "Command request") == 0)
        return 8;
    if (__builtin_strcmp(str, "config_reset only available when shutdown") == 0)
        return 9;
    if (__builtin_strcmp(str, "oids already allocated") == 0)
        return 10;
    if (__builtin_strcmp(str, "Can't assign oid") == 0)
        return 11;
    if (__builtin_strcmp(str, "Invalid oid type") == 0)
        return 12;
    if (__builtin_strcmp(str, "Already finalized") == 0)
        return 13;
    if (__builtin_strcmp(str, "Invalid move request size") == 0)
        return 14;
    if (__builtin_strcmp(str, "Move queue overflow") == 0)
        return 15;
    if (__builtin_strcmp(str, "alloc_chunks failed") == 0)
        return 16;
    if (__builtin_strcmp(str, "alloc_chunk failed") == 0)
        return 17;
    if (__builtin_strcmp(str, "update_digital_out not valid with active queue") == 0)
        return 18;
    if (__builtin_strcmp(str, "Scheduled digital out event will exceed max_duration") == 0)
        return 19;
    if (__builtin_strcmp(str, "Can not set soft pwm cycle ticks while updates pending") == 0)
        return 20;
    if (__builtin_strcmp(str, "Missed scheduling of next digital out event") == 0)
        return 21;
    if (__builtin_strcmp(str, "Can't reset time when stepper active") == 0)
        return 22;
    if (__builtin_strcmp(str, "Invalid count parameter") == 0)
        return 23;
    if (__builtin_strcmp(str, "Stepper too far in past") == 0)
        return 24;
    if (__builtin_strcmp(str, "Can't add signal that is already active") == 0)
        return 25;
    if (__builtin_strcmp(str, "ADC out of range") == 0)
        return 26;
    if (__builtin_strcmp(str, "Invalid spi config") == 0)
        return 27;
    if (__builtin_strcmp(str, "I2C Timeout") == 0)
        return 28;
    if (__builtin_strcmp(str, "I2C START READ NACK") == 0)
        return 29;
    if (__builtin_strcmp(str, "I2C START NACK") == 0)
        return 30;
    if (__builtin_strcmp(str, "I2C NACK") == 0)
        return 31;
    if (__builtin_strcmp(str, "Scheduled pwm event will exceed max_duration") == 0)
        return 32;
    if (__builtin_strcmp(str, "Missed scheduling of next hard pwm event") == 0)
        return 33;
    if (__builtin_strcmp(str, "Invalid buttons retransmit count") == 0)
        return 34;
    if (__builtin_strcmp(str, "Set button past maximum button count") == 0)
        return 35;
    if (__builtin_strcmp(str, "Max of 8 buttons") == 0)
        return 36;
    if (__builtin_strcmp(str, "tmcuart data too large") == 0)
        return 37;
    if (__builtin_strcmp(str, "Invalid neopixel update command") == 0)
        return 38;
    if (__builtin_strcmp(str, "Invalid neopixel data_size") == 0)
        return 39;
    if (__builtin_strcmp(str, "Thermocouple reader fault") == 0)
        return 40;
    if (__builtin_strcmp(str, "Invalid thermocouple chip type") == 0)
        return 41;
    if (__builtin_strcmp(str, "angle sensor requires cs pin") == 0)
        return 42;
    if (__builtin_strcmp(str, "Invalid spi_angle chip type") == 0)
        return 43;
    if (__builtin_strcmp(str, "model type invalid") == 0)
        return 44;
    if (__builtin_strcmp(str, "bus_type invalid") == 0)
        return 45;
    if (__builtin_strcmp(str, "bus_type i2c unsupported") == 0)
        return 46;
    if (__builtin_strcmp(str, "bus_type spi unsupported") == 0)
        return 47;
    if (__builtin_strcmp(str, "HX71x gain/channel out of range 1-4") == 0)
        return 48;
    if (__builtin_strcmp(str, "Not a valid input pin") == 0)
        return 49;
    if (__builtin_strcmp(str, "Not an output pin") == 0)
        return 50;
    if (__builtin_strcmp(str, "Not a valid ADC pin") == 0)
        return 51;
    if (__builtin_strcmp(str, "Rescheduled timer in the past") == 0)
        return 52;
    if (__builtin_strcmp(str, "Failed to send i2c addr") == 0)
        return 53;
    if (__builtin_strcmp(str, "i2c timeout") == 0)
        return 54;
    if (__builtin_strcmp(str, "I2C NACK error encountered") == 0)
        return 55;
    if (__builtin_strcmp(str, "Unsupported i2c bus") == 0)
        return 56;
    if (__builtin_strcmp(str, "Invalid spi bus") == 0)
        return 57;
    if (__builtin_strcmp(str, "Another CAN node assigned this ID") == 0)
        return 58;
    if (__builtin_strcmp(str, "Invalid PWM channel") == 0)
        return 59;
    if (__builtin_strcmp(str, "PWM already programmed at different speed") == 0)
        return 60;
    if (__builtin_strcmp(str, "Not a valid PWM pin") == 0)
        return 61;
    return 0xff;
}

const struct initial_pin_s initial_pins[] PROGMEM = {
};
const int initial_pins_size PROGMEM = ARRAY_SIZE(initial_pins);

extern void DefaultHandler(void);
extern uint32_t _stack_end;
extern void ResetHandler(void);
extern void SysTick_Handler(void);
extern void CAN_IRQHandler(void);
extern void CAN_IRQHandler(void);
extern void CAN_IRQHandler(void);

const void *VectorTable[] __visible __section(".vector_table") = {
    &_stack_end,
    ResetHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    SysTick_Handler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    CAN_IRQHandler,
    CAN_IRQHandler,
    CAN_IRQHandler,
};

static const uint8_t command_parameters0[] PROGMEM = {
    PT_uint16 };
static const uint8_t command_parameters1[] PROGMEM = {
    PT_uint32, PT_uint16 };
static const uint8_t command_parameters2[] PROGMEM = {
    PT_uint32, PT_progmem_buffer };
static const uint8_t command_parameters3[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters4[] PROGMEM = {
    PT_uint32, PT_uint32 };
static const uint8_t command_parameters5[] PROGMEM = {
    PT_uint32 };
static const uint8_t command_parameters6[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint16 };
static const uint8_t command_parameters7[] PROGMEM = {
    PT_buffer };
static const uint8_t command_parameters8[] PROGMEM = {
    PT_byte, PT_int32 };
static const uint8_t command_parameters9[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters10[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters11[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters12[] PROGMEM = {
    PT_byte, PT_buffer };
static const uint8_t command_parameters13[] PROGMEM = {
    PT_byte, PT_byte, PT_buffer };
static const uint8_t command_parameters14[] PROGMEM = {
    PT_byte, PT_byte };
static const uint8_t command_parameters15[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters16[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters17[] PROGMEM = {
    PT_byte, PT_uint32, PT_buffer };
static const uint8_t command_parameters18[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters19[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint32, PT_uint16 };
static const uint8_t command_parameters20[] PROGMEM = {
    PT_byte, PT_uint16, PT_buffer };
static const uint8_t command_parameters21[] PROGMEM = {
    PT_progmem_buffer, PT_uint32 };
static const uint8_t command_parameters22[] PROGMEM = {
    PT_uint32, PT_byte };
static const uint8_t command_parameters23[] PROGMEM = {
    PT_byte };
static const uint8_t command_parameters24[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters25[] PROGMEM = {
    PT_byte, PT_uint32 };
static const uint8_t command_parameters26[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters27[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_int16 };
static const uint8_t command_parameters28[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters29[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters30[] PROGMEM = {
    PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters31[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_uint16, PT_uint16, PT_byte };
static const uint8_t command_parameters32[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters33[] PROGMEM = {
    PT_byte, PT_buffer, PT_uint32 };
static const uint8_t command_parameters34[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint16 };
static const uint8_t command_parameters35[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint16, PT_uint32 };
static const uint8_t command_parameters36[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte };
static const uint8_t command_parameters37[] PROGMEM = {
    PT_byte, PT_buffer, PT_byte };
static const uint8_t command_parameters38[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters39[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_uint32, PT_uint32 };
static const uint8_t command_parameters40[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters41[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters42[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters43[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters44[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters45[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters46[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_uint32 };

const struct command_encoder command_encoder_93 PROGMEM = {    
    // starting
    .encoded_msgid=93, // msgid=93
    .num_params=0,
    .param_types = 0,
    .max_size=6,
};
const struct command_encoder command_encoder_94 PROGMEM = {    
    // is_shutdown static_string_id=%hu
    .encoded_msgid=94, // msgid=94
    .num_params=1,
    .param_types = command_parameters0,
    .max_size=9,
};
const struct command_encoder command_encoder_95 PROGMEM = {    
    // shutdown clock=%u static_string_id=%hu
    .encoded_msgid=95, // msgid=95
    .num_params=2,
    .param_types = command_parameters1,
    .max_size=14,
};
const struct command_encoder command_encoder_0 PROGMEM = {    
    // identify_response offset=%u data=%.*s
    .encoded_msgid=0, // msgid=0
    .num_params=2,
    .param_types = command_parameters2,
    .max_size=64,
};
const struct command_encoder command_encoder_96 PROGMEM = {    
    // stats count=%u sum=%u sumsq=%u
    .encoded_msgid=96, // msgid=-32
    .num_params=3,
    .param_types = command_parameters3,
    .max_size=21,
};
const struct command_encoder command_encoder_97 PROGMEM = {    
    // uptime high=%u clock=%u
    .encoded_msgid=97, // msgid=-31
    .num_params=2,
    .param_types = command_parameters4,
    .max_size=16,
};
const struct command_encoder command_encoder_98 PROGMEM = {    
    // clock clock=%u
    .encoded_msgid=98, // msgid=-30
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_99 PROGMEM = {    
    // config is_config=%c crc=%u is_shutdown=%c move_count=%hu
    .encoded_msgid=99, // msgid=-29
    .num_params=4,
    .param_types = command_parameters6,
    .max_size=18,
};
const struct command_encoder command_encoder_100 PROGMEM = {    
    // pong data=%*s
    .encoded_msgid=100, // msgid=-28
    .num_params=1,
    .param_types = command_parameters7,
    .max_size=64,
};
const struct command_encoder command_encoder_101 PROGMEM = {    
    // debug_result val=%u
    .encoded_msgid=101, // msgid=-27
    .num_params=1,
    .param_types = command_parameters5,
    .max_size=11,
};
const struct command_encoder command_encoder_102 PROGMEM = {    
    // stepper_position oid=%c pos=%i
    .encoded_msgid=102, // msgid=-26
    .num_params=2,
    .param_types = command_parameters8,
    .max_size=13,
};
const struct command_encoder command_encoder_103 PROGMEM = {    
    // endstop_state oid=%c homing=%c next_clock=%u pin_value=%c
    .encoded_msgid=103, // msgid=-25
    .num_params=4,
    .param_types = command_parameters9,
    .max_size=17,
};
const struct command_encoder command_encoder_104 PROGMEM = {    
    // trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u
    .encoded_msgid=104, // msgid=-24
    .num_params=4,
    .param_types = command_parameters10,
    .max_size=17,
};
const struct command_encoder command_encoder_105 PROGMEM = {    
    // analog_in_state oid=%c next_clock=%u value=%hu
    .encoded_msgid=105, // msgid=-23
    .num_params=3,
    .param_types = command_parameters11,
    .max_size=16,
};
const struct command_encoder command_encoder_106 PROGMEM = {    
    // spi_transfer_response oid=%c response=%*s
    .encoded_msgid=106, // msgid=-22
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_107 PROGMEM = {    
    // i2c_read_response oid=%c response=%*s
    .encoded_msgid=107, // msgid=-21
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_108 PROGMEM = {    
    // buttons_state oid=%c ack_count=%c state=%*s
    .encoded_msgid=108, // msgid=-20
    .num_params=3,
    .param_types = command_parameters13,
    .max_size=64,
};
const struct command_encoder command_encoder_109 PROGMEM = {    
    // tmcuart_response oid=%c read=%*s
    .encoded_msgid=109, // msgid=-19
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=64,
};
const struct command_encoder command_encoder_110 PROGMEM = {    
    // neopixel_result oid=%c success=%c
    .encoded_msgid=110, // msgid=-18
    .num_params=2,
    .param_types = command_parameters14,
    .max_size=10,
};
const struct command_encoder command_encoder_111 PROGMEM = {    
    // counter_state oid=%c next_clock=%u count=%u count_clock=%u
    .encoded_msgid=111, // msgid=-17
    .num_params=4,
    .param_types = command_parameters15,
    .max_size=23,
};
const struct command_encoder command_encoder_112 PROGMEM = {    
    // thermocouple_result oid=%c next_clock=%u value=%u fault=%c
    .encoded_msgid=112, // msgid=-16
    .num_params=4,
    .param_types = command_parameters16,
    .max_size=20,
};
const struct command_encoder command_encoder_113 PROGMEM = {    
    // spi_angle_transfer_response oid=%c clock=%u response=%*s
    .encoded_msgid=113, // msgid=-15
    .num_params=3,
    .param_types = command_parameters17,
    .max_size=64,
};
const struct command_encoder command_encoder_114 PROGMEM = {    
    // ldc1612_home_state oid=%c homing=%c trigger_clock=%u
    .encoded_msgid=114, // msgid=-14
    .num_params=3,
    .param_types = command_parameters18,
    .max_size=15,
};
const struct command_encoder command_encoder_115 PROGMEM = {    
    // sensor_bulk_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%u possible_overflows=%hu
    .encoded_msgid=115, // msgid=-13
    .num_params=6,
    .param_types = command_parameters19,
    .max_size=29,
};
const struct command_encoder command_encoder_116 PROGMEM = {    
    // sensor_bulk_data oid=%c sequence=%hu data=%*s
    .encoded_msgid=116, // msgid=-12
    .num_params=3,
    .param_types = command_parameters20,
    .max_size=64,
};
const struct command_encoder command_encoder_117 PROGMEM = {    
    // canbus_id canbus_uuid=%.*s canbus_nodeid=%u
    .encoded_msgid=117, // msgid=-11
    .num_params=2,
    .param_types = command_parameters21,
    .max_size=64,
};

const __always_inline struct command_encoder *
ctr_lookup_encoder(const char *str)
{
    if (__builtin_strcmp(str, "starting") == 0)
        return &command_encoder_93;
    if (__builtin_strcmp(str, "is_shutdown static_string_id=%hu") == 0)
        return &command_encoder_94;
    if (__builtin_strcmp(str, "shutdown clock=%u static_string_id=%hu") == 0)
        return &command_encoder_95;
    if (__builtin_strcmp(str, "identify_response offset=%u data=%.*s") == 0)
        return &command_encoder_0;
    if (__builtin_strcmp(str, "stats count=%u sum=%u sumsq=%u") == 0)
        return &command_encoder_96;
    if (__builtin_strcmp(str, "uptime high=%u clock=%u") == 0)
        return &command_encoder_97;
    if (__builtin_strcmp(str, "clock clock=%u") == 0)
        return &command_encoder_98;
    if (__builtin_strcmp(str, "config is_config=%c crc=%u is_shutdown=%c move_count=%hu") == 0)
        return &command_encoder_99;
    if (__builtin_strcmp(str, "pong data=%*s") == 0)
        return &command_encoder_100;
    if (__builtin_strcmp(str, "debug_result val=%u") == 0)
        return &command_encoder_101;
    if (__builtin_strcmp(str, "stepper_position oid=%c pos=%i") == 0)
        return &command_encoder_102;
    if (__builtin_strcmp(str, "endstop_state oid=%c homing=%c next_clock=%u pin_value=%c") == 0)
        return &command_encoder_103;
    if (__builtin_strcmp(str, "trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u") == 0)
        return &command_encoder_104;
    if (__builtin_strcmp(str, "analog_in_state oid=%c next_clock=%u value=%hu") == 0)
        return &command_encoder_105;
    if (__builtin_strcmp(str, "spi_transfer_response oid=%c response=%*s") == 0)
        return &command_encoder_106;
    if (__builtin_strcmp(str, "i2c_read_response oid=%c response=%*s") == 0)
        return &command_encoder_107;
    if (__builtin_strcmp(str, "buttons_state oid=%c ack_count=%c state=%*s") == 0)
        return &command_encoder_108;
    if (__builtin_strcmp(str, "tmcuart_response oid=%c read=%*s") == 0)
        return &command_encoder_109;
    if (__builtin_strcmp(str, "neopixel_result oid=%c success=%c") == 0)
        return &command_encoder_110;
    if (__builtin_strcmp(str, "counter_state oid=%c next_clock=%u count=%u count_clock=%u") == 0)
        return &command_encoder_111;
    if (__builtin_strcmp(str, "thermocouple_result oid=%c next_clock=%u value=%u fault=%c") == 0)
        return &command_encoder_112;
    if (__builtin_strcmp(str, "spi_angle_transfer_response oid=%c clock=%u response=%*s") == 0)
        return &command_encoder_113;
    if (__builtin_strcmp(str, "ldc1612_home_state oid=%c homing=%c trigger_clock=%u") == 0)
        return &command_encoder_114;
    if (__builtin_strcmp(str, "sensor_bulk_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%u possible_overflows=%hu") == 0)
        return &command_encoder_115;
    if (__builtin_strcmp(str, "sensor_bulk_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_116;
    if (__builtin_strcmp(str, "canbus_id canbus_uuid=%.*s canbus_nodeid=%u") == 0)
        return &command_encoder_117;
    return NULL;
}

const __always_inline struct command_encoder *
ctr_lookup_output(const char *str)
{
    
    return NULL;
}

extern void command_allocate_oids(uint32_t*);
extern void command_buttons_ack(uint32_t*);
extern void command_buttons_add(uint32_t*);
extern void command_buttons_query(uint32_t*);
extern void command_clear_shutdown(uint32_t*);
extern void command_config_ads1220(uint32_t*);
extern void command_config_adxl345(uint32_t*);
extern void command_config_analog_in(uint32_t*);
extern void command_config_buttons(uint32_t*);
extern void command_config_counter(uint32_t*);
extern void command_config_digital_out(uint32_t*);
extern void command_config_endstop(uint32_t*);
extern void command_config_hd44780(uint32_t*);
extern void command_config_hx71x(uint32_t*);
extern void command_config_i2c(uint32_t*);
extern void command_config_ldc1612(uint32_t*);
extern void command_config_ldc1612_with_intb(uint32_t*);
extern void command_config_lis2dw(uint32_t*);
extern void command_config_mpu9250(uint32_t*);
extern void command_config_neopixel(uint32_t*);
extern void command_config_pwm_out(uint32_t*);
extern void command_config_spi(uint32_t*);
extern void command_config_spi_angle(uint32_t*);
extern void command_config_spi_shutdown(uint32_t*);
extern void command_config_spi_without_cs(uint32_t*);
extern void command_config_st7920(uint32_t*);
extern void command_config_stepper(uint32_t*);
extern void command_config_thermocouple(uint32_t*);
extern void command_config_tmcuart(uint32_t*);
extern void command_config_trsync(uint32_t*);
extern void command_debug_nop(uint32_t*);
extern void command_debug_ping(uint32_t*);
extern void command_debug_read(uint32_t*);
extern void command_debug_write(uint32_t*);
extern void command_emergency_stop(uint32_t*);
extern void command_endstop_home(uint32_t*);
extern void command_endstop_query_state(uint32_t*);
extern void command_finalize_config(uint32_t*);
extern void command_get_canbus_id(uint32_t*);
extern void command_get_clock(uint32_t*);
extern void command_get_config(uint32_t*);
extern void command_get_uptime(uint32_t*);
extern void command_hd44780_send_cmds(uint32_t*);
extern void command_hd44780_send_data(uint32_t*);
extern void command_i2c_read(uint32_t*);
extern void command_i2c_set_bus(uint32_t*);
extern void command_i2c_set_software_bus(uint32_t*);
extern void command_i2c_write(uint32_t*);
extern void command_identify(uint32_t*);
extern void command_ldc1612_setup_home(uint32_t*);
extern void command_neopixel_send(uint32_t*);
extern void command_neopixel_update(uint32_t*);
extern void command_query_ads1220(uint32_t*);
extern void command_query_ads1220_status(uint32_t*);
extern void command_query_adxl345(uint32_t*);
extern void command_query_adxl345_status(uint32_t*);
extern void command_query_analog_in(uint32_t*);
extern void command_query_counter(uint32_t*);
extern void command_query_hx71x(uint32_t*);
extern void command_query_hx71x_status(uint32_t*);
extern void command_query_ldc1612(uint32_t*);
extern void command_query_ldc1612_home_state(uint32_t*);
extern void command_query_lis2dw(uint32_t*);
extern void command_query_lis2dw_status(uint32_t*);
extern void command_query_mpu9250(uint32_t*);
extern void command_query_mpu9250_status(uint32_t*);
extern void command_query_spi_angle(uint32_t*);
extern void command_query_status_ldc1612(uint32_t*);
extern void command_query_thermocouple(uint32_t*);
extern void command_queue_digital_out(uint32_t*);
extern void command_queue_pwm_out(uint32_t*);
extern void command_queue_step(uint32_t*);
extern void command_reset(uint32_t*);
extern void command_reset_step_clock(uint32_t*);
extern void command_set_digital_out(uint32_t*);
extern void command_set_digital_out_pwm_cycle(uint32_t*);
extern void command_set_next_step_dir(uint32_t*);
extern void command_set_pwm_out(uint32_t*);
extern void command_spi_angle_transfer(uint32_t*);
extern void command_spi_send(uint32_t*);
extern void command_spi_set_bus(uint32_t*);
extern void command_spi_set_software_bus(uint32_t*);
extern void command_spi_transfer(uint32_t*);
extern void command_st7920_send_cmds(uint32_t*);
extern void command_st7920_send_data(uint32_t*);
extern void command_stepper_get_position(uint32_t*);
extern void command_stepper_stop_on_trigger(uint32_t*);
extern void command_tmcuart_send(uint32_t*);
extern void command_trsync_set_timeout(uint32_t*);
extern void command_trsync_start(uint32_t*);
extern void command_trsync_trigger(uint32_t*);
extern void command_update_digital_out(uint32_t*);

const struct command_parser command_index[] PROGMEM = {
{
}, {
    // identify offset=%u count=%c
    .encoded_msgid=1, // msgid=1
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0x01,
    .func=command_identify
}, {
    // clear_shutdown
    .encoded_msgid=2, // msgid=2
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_clear_shutdown
}, {
    // emergency_stop
    .encoded_msgid=3, // msgid=3
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_emergency_stop
}, {
    // get_uptime
    .encoded_msgid=4, // msgid=4
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_uptime
}, {
    // get_clock
    .encoded_msgid=5, // msgid=5
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_clock
}, {
    // finalize_config crc=%u
    .encoded_msgid=6, // msgid=6
    .num_params=1,
    .param_types = command_parameters5,
    .num_args=1,
    .flags=0,
    .func=command_finalize_config
}, {
    // get_config
    .encoded_msgid=7, // msgid=7
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_config
}, {
    // allocate_oids count=%c
    .encoded_msgid=8, // msgid=8
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_allocate_oids
}, {
    // debug_nop
    .encoded_msgid=9, // msgid=9
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_debug_nop
}, {
    // debug_ping data=%*s
    .encoded_msgid=10, // msgid=10
    .num_params=1,
    .param_types = command_parameters7,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_ping
}, {
    // debug_write order=%c addr=%u val=%u
    .encoded_msgid=11, // msgid=11
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0x01,
    .func=command_debug_write
}, {
    // debug_read order=%c addr=%u
    .encoded_msgid=12, // msgid=12
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_read
}, {
    // set_digital_out pin=%u value=%c
    .encoded_msgid=13, // msgid=13
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out
}, {
    // update_digital_out oid=%c value=%c
    .encoded_msgid=14, // msgid=14
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_update_digital_out
}, {
    // queue_digital_out oid=%c clock=%u on_ticks=%u
    .encoded_msgid=15, // msgid=15
    .num_params=3,
    .param_types = command_parameters24,
    .num_args=3,
    .flags=0,
    .func=command_queue_digital_out
}, {
    // set_digital_out_pwm_cycle oid=%c cycle_ticks=%u
    .encoded_msgid=16, // msgid=16
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out_pwm_cycle
}, {
    // config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u
    .encoded_msgid=17, // msgid=17
    .num_params=5,
    .param_types = command_parameters26,
    .num_args=5,
    .flags=0,
    .func=command_config_digital_out
}, {
    // stepper_stop_on_trigger oid=%c trsync_oid=%c
    .encoded_msgid=18, // msgid=18
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_stepper_stop_on_trigger
}, {
    // stepper_get_position oid=%c
    .encoded_msgid=19, // msgid=19
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_stepper_get_position
}, {
    // reset_step_clock oid=%c clock=%u
    .encoded_msgid=20, // msgid=20
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_reset_step_clock
}, {
    // set_next_step_dir oid=%c dir=%c
    .encoded_msgid=21, // msgid=21
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_set_next_step_dir
}, {
    // queue_step oid=%c interval=%u count=%hu add=%hi
    .encoded_msgid=22, // msgid=22
    .num_params=4,
    .param_types = command_parameters27,
    .num_args=4,
    .flags=0,
    .func=command_queue_step
}, {
    // config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u
    .encoded_msgid=23, // msgid=23
    .num_params=5,
    .param_types = command_parameters28,
    .num_args=5,
    .flags=0,
    .func=command_config_stepper
}, {
    // endstop_query_state oid=%c
    .encoded_msgid=24, // msgid=24
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_endstop_query_state
}, {
    // endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c
    .encoded_msgid=25, // msgid=25
    .num_params=8,
    .param_types = command_parameters29,
    .num_args=8,
    .flags=0,
    .func=command_endstop_home
}, {
    // config_endstop oid=%c pin=%c pull_up=%c
    .encoded_msgid=26, // msgid=26
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_endstop
}, {
    // trsync_trigger oid=%c reason=%c
    .encoded_msgid=27, // msgid=27
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_trsync_trigger
}, {
    // trsync_set_timeout oid=%c clock=%u
    .encoded_msgid=28, // msgid=28
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_trsync_set_timeout
}, {
    // trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c
    .encoded_msgid=29, // msgid=29
    .num_params=4,
    .param_types = command_parameters16,
    .num_args=4,
    .flags=0,
    .func=command_trsync_start
}, {
    // config_trsync oid=%c
    .encoded_msgid=30, // msgid=30
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_trsync
}, {
    // query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u min_value=%hu max_value=%hu range_check_count=%c
    .encoded_msgid=31, // msgid=31
    .num_params=8,
    .param_types = command_parameters31,
    .num_args=8,
    .flags=0,
    .func=command_query_analog_in
}, {
    // config_analog_in oid=%c pin=%u
    .encoded_msgid=32, // msgid=32
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_config_analog_in
}, {
    // config_spi_shutdown oid=%c spi_oid=%c shutdown_msg=%*s
    .encoded_msgid=33, // msgid=33
    .num_params=3,
    .param_types = command_parameters13,
    .num_args=4,
    .flags=0,
    .func=command_config_spi_shutdown
}, {
    // spi_send oid=%c data=%*s
    .encoded_msgid=34, // msgid=34
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_send
}, {
    // spi_transfer oid=%c data=%*s
    .encoded_msgid=35, // msgid=35
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_transfer
}, {
    // spi_set_bus oid=%c spi_bus=%u mode=%u rate=%u
    .encoded_msgid=36, // msgid=36
    .num_params=4,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_spi_set_bus
}, {
    // config_spi_without_cs oid=%c
    .encoded_msgid=37, // msgid=37
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_spi_without_cs
}, {
    // config_spi oid=%c pin=%u cs_active_high=%c
    .encoded_msgid=38, // msgid=38
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_spi
}, {
    // i2c_read oid=%c reg=%*s read_len=%u
    .encoded_msgid=39, // msgid=39
    .num_params=3,
    .param_types = command_parameters33,
    .num_args=4,
    .flags=0,
    .func=command_i2c_read
}, {
    // i2c_write oid=%c data=%*s
    .encoded_msgid=40, // msgid=40
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_i2c_write
}, {
    // i2c_set_bus oid=%c i2c_bus=%u rate=%u address=%u
    .encoded_msgid=41, // msgid=41
    .num_params=4,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_i2c_set_bus
}, {
    // config_i2c oid=%c
    .encoded_msgid=42, // msgid=42
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_i2c
}, {
    // set_pwm_out pin=%u cycle_ticks=%u value=%hu
    .encoded_msgid=43, // msgid=43
    .num_params=3,
    .param_types = command_parameters34,
    .num_args=3,
    .flags=0,
    .func=command_set_pwm_out
}, {
    // queue_pwm_out oid=%c clock=%u value=%hu
    .encoded_msgid=44, // msgid=44
    .num_params=3,
    .param_types = command_parameters11,
    .num_args=3,
    .flags=0,
    .func=command_queue_pwm_out
}, {
    // config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u
    .encoded_msgid=45, // msgid=45
    .num_params=6,
    .param_types = command_parameters35,
    .num_args=6,
    .flags=0,
    .func=command_config_pwm_out
}, {
    // buttons_ack oid=%c count=%c
    .encoded_msgid=46, // msgid=46
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_buttons_ack
}, {
    // buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c
    .encoded_msgid=47, // msgid=47
    .num_params=5,
    .param_types = command_parameters36,
    .num_args=5,
    .flags=0,
    .func=command_buttons_query
}, {
    // buttons_add oid=%c pos=%c pin=%u pull_up=%c
    .encoded_msgid=48, // msgid=48
    .num_params=4,
    .param_types = command_parameters9,
    .num_args=4,
    .flags=0,
    .func=command_buttons_add
}, {
    // config_buttons oid=%c button_count=%c
    .encoded_msgid=49, // msgid=49
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_buttons
}, {
    // tmcuart_send oid=%c write=%*s read=%c
    .encoded_msgid=50, // msgid=50
    .num_params=3,
    .param_types = command_parameters37,
    .num_args=4,
    .flags=0,
    .func=command_tmcuart_send
}, {
    // config_tmcuart oid=%c rx_pin=%u pull_up=%c tx_pin=%u bit_time=%u
    .encoded_msgid=51, // msgid=51
    .num_params=5,
    .param_types = command_parameters38,
    .num_args=5,
    .flags=0,
    .func=command_config_tmcuart
}, {
    // neopixel_send oid=%c
    .encoded_msgid=52, // msgid=52
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_neopixel_send
}, {
    // neopixel_update oid=%c pos=%hu data=%*s
    .encoded_msgid=53, // msgid=53
    .num_params=3,
    .param_types = command_parameters20,
    .num_args=4,
    .flags=0,
    .func=command_neopixel_update
}, {
    // config_neopixel oid=%c pin=%u data_size=%hu bit_max_ticks=%u reset_min_ticks=%u
    .encoded_msgid=54, // msgid=54
    .num_params=5,
    .param_types = command_parameters39,
    .num_args=5,
    .flags=0,
    .func=command_config_neopixel
}, {
    // query_counter oid=%c clock=%u poll_ticks=%u sample_ticks=%u
    .encoded_msgid=55, // msgid=55
    .num_params=4,
    .param_types = command_parameters15,
    .num_args=4,
    .flags=0,
    .func=command_query_counter
}, {
    // config_counter oid=%c pin=%u pull_up=%c
    .encoded_msgid=56, // msgid=56
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_counter
}, {
    // st7920_send_data oid=%c data=%*s
    .encoded_msgid=57, // msgid=57
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_data
}, {
    // st7920_send_cmds oid=%c cmds=%*s
    .encoded_msgid=58, // msgid=58
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_cmds
}, {
    // config_st7920 oid=%c cs_pin=%u sclk_pin=%u sid_pin=%u sync_delay_ticks=%u cmd_delay_ticks=%u
    .encoded_msgid=59, // msgid=59
    .num_params=6,
    .param_types = command_parameters40,
    .num_args=6,
    .flags=0,
    .func=command_config_st7920
}, {
    // hd44780_send_data oid=%c data=%*s
    .encoded_msgid=60, // msgid=60
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_data
}, {
    // hd44780_send_cmds oid=%c cmds=%*s
    .encoded_msgid=61, // msgid=61
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_cmds
}, {
    // config_hd44780 oid=%c rs_pin=%u e_pin=%u d4_pin=%u d5_pin=%u d6_pin=%u d7_pin=%u delay_ticks=%u
    .encoded_msgid=62, // msgid=62
    .num_params=8,
    .param_types = command_parameters41,
    .num_args=8,
    .flags=0,
    .func=command_config_hd44780
}, {
    // spi_set_software_bus oid=%c miso_pin=%u mosi_pin=%u sclk_pin=%u mode=%u rate=%u
    .encoded_msgid=63, // msgid=63
    .num_params=6,
    .param_types = command_parameters40,
    .num_args=6,
    .flags=0,
    .func=command_spi_set_software_bus
}, {
    // i2c_set_software_bus oid=%c scl_pin=%u sda_pin=%u rate=%u address=%u
    .encoded_msgid=64, // msgid=64
    .num_params=5,
    .param_types = command_parameters42,
    .num_args=5,
    .flags=0,
    .func=command_i2c_set_software_bus
}, {
    // query_thermocouple oid=%c clock=%u rest_ticks=%u min_value=%u max_value=%u max_invalid_count=%c
    .encoded_msgid=65, // msgid=65
    .num_params=6,
    .param_types = command_parameters43,
    .num_args=6,
    .flags=0,
    .func=command_query_thermocouple
}, {
    // config_thermocouple oid=%c spi_oid=%c thermocouple_type=%c
    .encoded_msgid=66, // msgid=66
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_thermocouple
}, {
    // query_adxl345_status oid=%c
    .encoded_msgid=67, // msgid=67
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_adxl345_status
}, {
    // query_adxl345 oid=%c rest_ticks=%u
    .encoded_msgid=68, // msgid=68
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_adxl345
}, {
    // config_adxl345 oid=%c spi_oid=%c
    .encoded_msgid=69, // msgid=69
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_adxl345
}, {
    // spi_angle_transfer oid=%c data=%*s
    .encoded_msgid=70, // msgid=70
    .num_params=2,
    .param_types = command_parameters12,
    .num_args=3,
    .flags=0,
    .func=command_spi_angle_transfer
}, {
    // query_spi_angle oid=%c clock=%u rest_ticks=%u time_shift=%c
    .encoded_msgid=71, // msgid=71
    .num_params=4,
    .param_types = command_parameters16,
    .num_args=4,
    .flags=0,
    .func=command_query_spi_angle
}, {
    // config_spi_angle oid=%c spi_oid=%c spi_angle_type=%c
    .encoded_msgid=72, // msgid=72
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_spi_angle
}, {
    // query_mpu9250_status oid=%c
    .encoded_msgid=73, // msgid=73
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_mpu9250_status
}, {
    // query_mpu9250 oid=%c rest_ticks=%u
    .encoded_msgid=74, // msgid=74
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_mpu9250
}, {
    // config_mpu9250 oid=%c i2c_oid=%c
    .encoded_msgid=75, // msgid=75
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_mpu9250
}, {
    // query_lis2dw_status oid=%c
    .encoded_msgid=76, // msgid=76
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_lis2dw_status
}, {
    // query_lis2dw oid=%c rest_ticks=%u
    .encoded_msgid=77, // msgid=77
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_lis2dw
}, {
    // config_lis2dw oid=%c bus_oid=%c bus_oid_type=%c lis_chip_type=%c
    .encoded_msgid=78, // msgid=78
    .num_params=4,
    .param_types = command_parameters44,
    .num_args=4,
    .flags=0,
    .func=command_config_lis2dw
}, {
    // query_status_ldc1612 oid=%c
    .encoded_msgid=79, // msgid=79
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_status_ldc1612
}, {
    // query_ldc1612 oid=%c rest_ticks=%u
    .encoded_msgid=80, // msgid=80
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_ldc1612
}, {
    // query_ldc1612_home_state oid=%c
    .encoded_msgid=81, // msgid=81
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_ldc1612_home_state
}, {
    // ldc1612_setup_home oid=%c clock=%u threshold=%u trsync_oid=%c trigger_reason=%c error_reason=%c
    .encoded_msgid=82, // msgid=82
    .num_params=6,
    .param_types = command_parameters45,
    .num_args=6,
    .flags=0,
    .func=command_ldc1612_setup_home
}, {
    // config_ldc1612_with_intb oid=%c i2c_oid=%c intb_pin=%c
    .encoded_msgid=83, // msgid=83
    .num_params=3,
    .param_types = command_parameters30,
    .num_args=3,
    .flags=0,
    .func=command_config_ldc1612_with_intb
}, {
    // config_ldc1612 oid=%c i2c_oid=%c
    .encoded_msgid=84, // msgid=84
    .num_params=2,
    .param_types = command_parameters14,
    .num_args=2,
    .flags=0,
    .func=command_config_ldc1612
}, {
    // query_hx71x_status oid=%c
    .encoded_msgid=85, // msgid=85
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_hx71x_status
}, {
    // query_hx71x oid=%c rest_ticks=%u
    .encoded_msgid=86, // msgid=86
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_hx71x
}, {
    // config_hx71x oid=%c gain_channel=%c dout_pin=%u sclk_pin=%u
    .encoded_msgid=87, // msgid=87
    .num_params=4,
    .param_types = command_parameters46,
    .num_args=4,
    .flags=0,
    .func=command_config_hx71x
}, {
    // query_ads1220_status oid=%c
    .encoded_msgid=88, // msgid=88
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_ads1220_status
}, {
    // query_ads1220 oid=%c rest_ticks=%u
    .encoded_msgid=89, // msgid=89
    .num_params=2,
    .param_types = command_parameters25,
    .num_args=2,
    .flags=0,
    .func=command_query_ads1220
}, {
    // config_ads1220 oid=%c spi_oid=%c data_ready_pin=%u
    .encoded_msgid=90, // msgid=90
    .num_params=3,
    .param_types = command_parameters18,
    .num_args=3,
    .flags=0,
    .func=command_config_ads1220
}, {
    // reset
    .encoded_msgid=91, // msgid=91
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_reset
}, {
    // get_canbus_id
    .encoded_msgid=92, // msgid=92
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_canbus_id
},
};

const uint16_t command_index_size PROGMEM = ARRAY_SIZE(command_index);

// version: v0.12.0-358-gc88ee84be
// build_versions: gcc: (15:10.3-2021.07-4) 10.3.1 20210621 (release) binutils: (2.38-3ubuntu1+15build1) 2.38

const uint8_t command_identify_data[] PROGMEM = {
    0x78, 0xda, 0x9d, 0x1a, 0x6b, 0x6f, 0xdb, 0xc8,
    0xf1, 0xaf, 0x2c, 0x04, 0x04, 0xbd, 0xf4, 0x62,
    0x57, 0x24, 0x45, 0x4a, 0x32, 0x90, 0x0f, 0x8a,
    0xad, 0x24, 0x46, 0x62, 0xc7, 0x67, 0xd9, 0xcd,
    0x15, 0x45, 0x41, 0xd0, 0xe4, 0x4a, 0x22, 0xc2,
    0xd7, 0x71, 0x49, 0x3f, 0x7a, 0xc8, 0x7f, 0xef,
    0xcc, 0xce, 0xbe, 0x48, 0x29, 0x39, 0xa0, 0x07,
    0x24, 0xe1, 0xee, 0xce, 0xcc, 0xce, 0xcc, 0xce,
    0x5b, 0xf7, 0xe7, 0x24, 0x69, 0x9a, 0xc9, 0xd9,
    0xe4, 0x53, 0x91, 0x37, 0x0d, 0x6f, 0x27, 0x6f,
    0x26, 0x0f, 0x7d, 0x5e, 0x64, 0xf1, 0x23, 0x6f,
    0x45, 0x5e, 0x57, 0x02, 0x8e, 0x76, 0x69, 0x7a,
    0xc6, 0x7e, 0xf1, 0xc2, 0x33, 0x6f, 0x7a, 0x1a,
    0x9c, 0xf8, 0x53, 0xdf, 0x3b, 0x9d, 0xce, 0x4f,
    0x66, 0xaf, 0x19, 0xae, 0x4f, 0x3d, 0x86, 0x3b,
    0xd3, 0xc8, 0xf7, 0xd8, 0x2f, 0x2d, 0x2f, 0x78,
    0x22, 0xf8, 0x6b, 0xf6, 0x90, 0x57, 0x7d, 0x97,
    0x17, 0x02, 0xf0, 0xfc, 0xd3, 0x60, 0x71, 0x12,
    0xf4, 0x0f, 0x7d, 0xd5, 0xf5, 0xde, 0xaf, 0x5e,
    0x28, 0xc9, 0x7b, 0xaf, 0x19, 0xee, 0xc3, 0x6d,
    0x69, 0x5d, 0x96, 0x49, 0x95, 0xc1, 0x3d, 0x7f,
    0x4e, 0x92, 0xa2, 0xa8, 0xd3, 0xa4, 0xe3, 0x71,
    0x9d, 0x67, 0x82, 0xa5, 0x35, 0xa0, 0xbc, 0x7d,
    0x95, 0x4e, 0xce, 0x16, 0xc8, 0x54, 0xd7, 0x01,
    0x37, 0x71, 0x92, 0x7e, 0x63, 0x70, 0x0a, 0xdb,
    0xce, 0xf9, 0x2c, 0x72, 0x00, 0xb2, 0x4c, 0x03,
    0x34, 0xb5, 0x90, 0xff, 0xe4, 0xd5, 0xdb, 0x57,
    0x3d, 0x6b, 0xfa, 0xa2, 0x88, 0xfb, 0x86, 0x10,
    0x1c, 0x8a, 0x7f, 0xf4, 0xbc, 0x7d, 0x31, 0x34,
    0x81, 0x81, 0x6f, 0x08, 0xdd, 0x72, 0xd1, 0xc5,
    0x5d, 0x9e, 0x7e, 0x13, 0xb4, 0xea, 0xda, 0xa4,
    0x12, 0x65, 0xde, 0xc5, 0xfa, 0x56, 0x96, 0x57,
    0xa0, 0x22, 0x75, 0xff, 0x1c, 0xe4, 0x00, 0xc9,
    0xdb, 0x58, 0xec, 0xfb, 0x2e, 0xab, 0x9f, 0xaa,
    0xc9, 0x99, 0x8f, 0xa2, 0x55, 0xdb, 0x7c, 0x07,
    0x1c, 0x09, 0xcf, 0xf7, 0xa7, 0xfa, 0x0a, 0xd1,
    0xe4, 0xb1, 0xfa, 0xcc, 0x92, 0x2e, 0x89, 0x5b,
    0x9e, 0x64, 0x2f, 0x31, 0x31, 0x39, 0x39, 0x5b,
    0x4e, 0x1d, 0xbc, 0xe7, 0x22, 0x98, 0x85, 0x87,
    0x78, 0x93, 0xb3, 0x68, 0x69, 0xa1, 0xaa, 0xa4,
    0xa8, 0x77, 0x71, 0x5e, 0x19, 0xa9, 0x15, 0xa5,
    0xc0, 0x72, 0xa0, 0x44, 0xd5, 0x10, 0xb4, 0x8c,
    0x1d, 0xfd, 0x59, 0x72, 0x72, 0x93, 0xb7, 0x43,
    0x62, 0x03, 0xdd, 0x85, 0x91, 0x01, 0xce, 0xf2,
    0x5d, 0xde, 0x25, 0x45, 0x5c, 0xf7, 0xdd, 0x08,
    0xe1, 0x31, 0x29, 0x7a, 0x2e, 0x45, 0xe4, 0xdb,
    0xa4, 0x2f, 0xba, 0xd8, 0x6c, 0x94, 0xc9, 0x73,
    0x9c, 0xf5, 0x6d, 0xd2, 0x81, 0x71, 0x49, 0x3e,
    0xbd, 0xb9, 0xa1, 0xc7, 0xc1, 0x0e, 0xba, 0xba,
    0x19, 0xd0, 0x4a, 0x07, 0x97, 0xfb, 0xf6, 0xf2,
    0x7d, 0x36, 0x9b, 0xcd, 0x17, 0x46, 0xad, 0xad,
    0x50, 0x3a, 0x64, 0x5c, 0x7f, 0x64, 0x33, 0xf3,
    0x15, 0x9a, 0xaf, 0xc8, 0x7c, 0xcd, 0xcd, 0x17,
    0x2f, 0x92, 0x17, 0xf3, 0xd8, 0xa0, 0x5d, 0xab,
    0xb9, 0xfd, 0xf3, 0xdc, 0x7b, 0xd6, 0x57, 0xec,
    0x92, 0x1c, 0xb4, 0xb6, 0x4f, 0xaa, 0x8a, 0x17,
    0x52, 0x36, 0x90, 0x5b, 0xd3, 0x10, 0x69, 0xf1,
    0xcd, 0x3c, 0xe2, 0xc2, 0x8a, 0x94, 0xfb, 0x29,
    0xd3, 0xaf, 0x36, 0xb3, 0x74, 0x8b, 0x2c, 0xf5,
    0x22, 0xcf, 0xd7, 0x94, 0x01, 0xca, 0xbc, 0xed,
    0x62, 0x36, 0x86, 0x8a, 0x9f, 0xf2, 0x6e, 0x0f,
    0x2f, 0xdc, 0x3d, 0x1c, 0xc2, 0x33, 0xdc, 0xa6,
    0x8b, 0x11, 0x37, 0xb0, 0xb8, 0xb9, 0xf0, 0xb3,
    0x27, 0xfb, 0xe4, 0x22, 0x1e, 0x7e, 0xc6, 0xdd,
    0x4b, 0x23, 0x1f, 0x04, 0x00, 0x41, 0xa8, 0xbc,
    0xd1, 0x1b, 0x93, 0xb3, 0xf9, 0xc2, 0x50, 0x29,
    0x9b, 0x7e, 0xe9, 0x87, 0xd3, 0x63, 0x7c, 0xce,
    0x43, 0x03, 0x55, 0xf1, 0xba, 0xc9, 0x9f, 0x79,
    0x31, 0x32, 0x02, 0x69, 0xde, 0x22, 0xff, 0x2f,
    0x50, 0xdd, 0xf7, 0x10, 0x12, 0xba, 0x18, 0x1f,
    0xdf, 0x71, 0x2a, 0xc1, 0x61, 0x0b, 0x74, 0x6a,
    0x55, 0x1f, 0x5a, 0xe1, 0x9b, 0xa7, 0xf2, 0x88,
    0x61, 0xa5, 0x2f, 0xe0, 0x68, 0x96, 0x86, 0x32,
    0xab, 0x7d, 0x3f, 0x36, 0x34, 0xd8, 0x39, 0xb0,
    0xb4, 0x99, 0xe5, 0x18, 0x9c, 0x69, 0x4c, 0x18,
    0x63, 0x4b, 0x97, 0x3f, 0xf2, 0x78, 0x9f, 0xef,
    0xf6, 0x52, 0xc2, 0x60, 0xe1, 0xc2, 0x83, 0xa7,
    0xed, 0x0a, 0x7e, 0xc4, 0x8b, 0xcd, 0x99, 0xa3,
    0x41, 0x7f, 0x80, 0xa9, 0xa3, 0xc2, 0x31, 0x64,
    0x75, 0x14, 0x97, 0x62, 0xf7, 0xf6, 0xd5, 0xdf,
    0x21, 0x0c, 0x06, 0xc1, 0x00, 0x17, 0xdf, 0x1e,
    0xed, 0x2c, 0x15, 0xc6, 0x8e, 0x02, 0x6b, 0x5e,
    0xa2, 0x9b, 0x2f, 0x6d, 0x68, 0x49, 0xc5, 0x11,
    0x73, 0x64, 0x02, 0x1e, 0x5b, 0x7f, 0xbe, 0x54,
    0x69, 0x3c, 0x34, 0x77, 0x96, 0x96, 0x59, 0x3c,
    0xf6, 0x80, 0x70, 0xe9, 0xdc, 0xc0, 0x31, 0x2f,
    0x18, 0xd6, 0x61, 0xa9, 0xcc, 0x8d, 0x65, 0x79,
    0xab, 0x3f, 0x29, 0x18, 0x4a, 0x60, 0x0b, 0xd5,
    0x17, 0x82, 0x3b, 0x44, 0x7d, 0x2b, 0x58, 0xb7,
    0xe7, 0x6d, 0x59, 0x43, 0xac, 0x69, 0x8e, 0x6a,
    0xd4, 0x3d, 0xb6, 0x4a, 0x8d, 0xac, 0xef, 0x77,
    0x65, 0xda, 0x27, 0xad, 0xb1, 0x8d, 0xf6, 0x39,
    0x3e, 0x08, 0x54, 0xac, 0x33, 0x9b, 0x68, 0x79,
    0x5d, 0x5e, 0x72, 0x12, 0xcd, 0xb3, 0x54, 0x5a,
    0xd4, 0x87, 0x55, 0x2b, 0x84, 0xde, 0x8c, 0x3f,
    0xf4, 0x60, 0xcf, 0x35, 0x64, 0xc4, 0xa5, 0x5e,
    0x01, 0x95, 0x9d, 0xb4, 0x65, 0x7a, 0x1f, 0xcf,
    0x80, 0x61, 0xe4, 0x66, 0x75, 0x9b, 0xf1, 0x16,
    0xef, 0x83, 0xc4, 0xd3, 0x52, 0x40, 0xf3, 0x35,
    0xc0, 0x53, 0x9b, 0x77, 0xfc, 0x00, 0x02, 0x8d,
    0x96, 0x00, 0x81, 0x15, 0x5e, 0xf2, 0x76, 0xc7,
    0xab, 0xf4, 0x25, 0xc6, 0xc8, 0x07, 0x4c, 0xc0,
    0x16, 0x45, 0xc1, 0x78, 0x5f, 0x97, 0xfc, 0x20,
    0x2f, 0x89, 0xa4, 0x6c, 0x5c, 0x07, 0x50, 0x6b,
    0x93, 0x95, 0x86, 0x79, 0x0b, 0x58, 0xb7, 0x91,
    0x97, 0xc4, 0x35, 0x3a, 0x6e, 0xf3, 0xdd, 0x8e,
    0xb7, 0x28, 0x84, 0xa8, 0x29, 0x7a, 0xf8, 0xa1,
    0xbd, 0x5c, 0x66, 0x45, 0xe0, 0x29, 0xe9, 0xb8,
    0x51, 0x90, 0x0f, 0xce, 0xb9, 0xcd, 0x21, 0xdf,
    0x80, 0x4b, 0xc7, 0xa4, 0x43, 0x96, 0xb6, 0x29,
    0xc5, 0xcc, 0x37, 0x93, 0x1d, 0x78, 0x73, 0x9a,
    0x54, 0x18, 0x5f, 0xf2, 0x0c, 0xf4, 0xe7, 0xab,
    0x2d, 0x64, 0x1d, 0xf4, 0xae, 0x56, 0x12, 0x0d,
    0x3c, 0x84, 0x96, 0x7d, 0x83, 0x0f, 0x03, 0xae,
    0xf9, 0x66, 0xa2, 0xe2, 0x79, 0x2c, 0x80, 0x85,
    0x18, 0x8c, 0xd2, 0xa4, 0x2b, 0xfc, 0x26, 0xd5,
    0x47, 0xde, 0x08, 0x0c, 0x5f, 0x85, 0x39, 0xc9,
    0x54, 0x81, 0xc1, 0x0b, 0x61, 0xa4, 0xa2, 0xf7,
    0x51, 0x26, 0xc2, 0xa5, 0x7b, 0x31, 0xdc, 0x8b,
    0x0b, 0xae, 0x52, 0xe4, 0x92, 0x00, 0x31, 0x0e,
    0x01, 0xdb, 0x6e, 0x94, 0x83, 0xa5, 0x8c, 0x51,
    0x20, 0x3f, 0xfe, 0x8b, 0x4f, 0xc7, 0x05, 0xd9,
    0xf1, 0xcc, 0xb3, 0x58, 0xa2, 0xde, 0x76, 0x4f,
    0x49, 0xcb, 0x5d, 0x74, 0xf0, 0x3d, 0xe3, 0x6f,
    0x59, 0xa2, 0x3f, 0x8f, 0x51, 0x8a, 0x66, 0x44,
    0x49, 0xd9, 0xc9, 0x58, 0x8e, 0x19, 0xca, 0x91,
    0xf1, 0xaa, 0xcb, 0xb7, 0x50, 0xa0, 0x6c, 0xb7,
    0x70, 0xa1, 0x74, 0x58, 0x93, 0xb7, 0x81, 0x11,
    0x9d, 0x22, 0xe0, 0xac, 0xff, 0x81, 0xc9, 0x74,
    0x7b, 0xb8, 0x70, 0x5f, 0x17, 0x99, 0x5c, 0xfc,
    0xdc, 0x08, 0x18, 0x6f, 0xdb, 0x7a, 0x60, 0x14,
    0x0b, 0x78, 0x46, 0x1d, 0xdf, 0xa5, 0xd2, 0x8d,
    0x39, 0x84, 0xee, 0x49, 0xdf, 0x64, 0xd6, 0x54,
    0xa8, 0xf2, 0xda, 0xf7, 0x8e, 0x2c, 0x21, 0x18,
    0x36, 0xd9, 0xd4, 0xa8, 0x1c, 0x1a, 0x18, 0x2c,
    0x5c, 0xb7, 0x1c, 0xc1, 0x49, 0x1b, 0xec, 0x6d,
    0xf0, 0x5b, 0x2c, 0x2c, 0xc0, 0xa0, 0x3e, 0x1a,
    0x11, 0x8a, 0xc6, 0x70, 0x63, 0x42, 0xd1, 0xdc,
    0x00, 0x8c, 0x4b, 0xa8, 0xff, 0xd3, 0xdb, 0x4a,
    0xeb, 0x6d, 0x2a, 0xfd, 0xd8, 0x15, 0x94, 0x8f,
    0x3b, 0x40, 0xdc, 0xf3, 0xf4, 0x9b, 0x53, 0x78,
    0x05, 0x9e, 0xe6, 0x61, 0x54, 0x77, 0x19, 0x0e,
    0x9a, 0x1a, 0x02, 0xda, 0xf8, 0x7e, 0x27, 0x50,
    0x87, 0x9a, 0xc0, 0xa0, 0x52, 0x19, 0x2b, 0x35,
    0x1a, 0x40, 0x1d, 0xa8, 0xd4, 0x10, 0x19, 0x95,
    0x25, 0x63, 0x32, 0xd3, 0x11, 0x9c, 0xb4, 0xb7,
    0x51, 0x90, 0x58, 0x18, 0x91, 0x86, 0x15, 0xc8,
    0x88, 0xd6, 0x7c, 0x3e, 0x04, 0x1b, 0xf3, 0x34,
    0x37, 0x2c, 0x8f, 0x4a, 0x90, 0x31, 0x9d, 0xd9,
    0x08, 0xee, 0x80, 0x90, 0x31, 0xbc, 0x83, 0x1c,
    0xfe, 0x83, 0x62, 0x1f, 0x23, 0x12, 0xa4, 0xec,
    0x7c, 0x4b, 0x6f, 0x34, 0x37, 0x02, 0x11, 0xe5,
    0x91, 0x92, 0x00, 0xc0, 0x98, 0xec, 0xb1, 0xb4,
    0xf6, 0x83, 0x4b, 0x1c, 0x5b, 0x19, 0x98, 0x0a,
    0x2d, 0x20, 0x9d, 0x42, 0x94, 0xcd, 0x1c, 0x4b,
    0x89, 0xe8, 0x8d, 0x7a, 0x7e, 0xac, 0xe8, 0x36,
    0x77, 0xd4, 0x6e, 0x2d, 0xe5, 0x19, 0x94, 0x51,
    0x29, 0x65, 0xc0, 0x8d, 0x79, 0x42, 0xac, 0x99,
    0x69, 0x60, 0xcc, 0xdd, 0xcc, 0x16, 0x97, 0xbc,
    0xa5, 0x74, 0xa5, 0xc3, 0xce, 0x5e, 0x86, 0x30,
    0xf8, 0x37, 0x87, 0x84, 0x00, 0x11, 0x40, 0x56,
    0x71, 0x10, 0xed, 0x3d, 0xf5, 0x29, 0xf1, 0x29,
    0xe8, 0x8f, 0xef, 0x03, 0x04, 0xb0, 0x20, 0x84,
    0x71, 0x65, 0x18, 0x75, 0x0c, 0xc0, 0x77, 0x70,
    0x00, 0x24, 0x25, 0x90, 0xa5, 0x9f, 0xa1, 0x39,
    0xa8, 0x03, 0x01, 0x29, 0x22, 0xa4, 0x8a, 0x3f,
    0x2b, 0x16, 0xa0, 0x3a, 0x31, 0x21, 0x35, 0x6f,
    0x29, 0x81, 0x79, 0x04, 0xa4, 0xf5, 0xf1, 0x17,
    0x35, 0x25, 0x68, 0x05, 0x59, 0xb1, 0xe5, 0x1d,
    0xf6, 0x80, 0x5b, 0xeb, 0xa4, 0x36, 0xba, 0xcd,
    0xa7, 0x04, 0xe7, 0xc4, 0x47, 0xe7, 0x34, 0x98,
    0xe9, 0xd3, 0x41, 0x9a, 0xc1, 0x2d, 0x95, 0x66,
    0xca, 0x3a, 0xe3, 0x4e, 0x92, 0x00, 0x94, 0xc8,
    0xa2, 0x1c, 0xcb, 0x31, 0x65, 0x2e, 0x6a, 0x9d,
    0x59, 0xca, 0x5a, 0xe4, 0xc7, 0xea, 0xbe, 0x03,
    0xa2, 0x91, 0x92, 0xe6, 0xc7, 0x72, 0x04, 0x60,
    0x32, 0x54, 0x52, 0xfe, 0x2c, 0x0d, 0x87, 0x8b,
    0x21, 0xd4, 0xf1, 0x2c, 0x1c, 0xce, 0x11, 0x4a,
    0x16, 0x8f, 0x31, 0xa6, 0x7a, 0xc8, 0x09, 0x39,
    0x96, 0xe2, 0xc6, 0x6f, 0xbc, 0xa5, 0x05, 0x90,
    0x35, 0x07, 0x5a, 0x2f, 0x25, 0x24, 0x66, 0xf2,
    0x93, 0x93, 0xad, 0x00, 0x03, 0x2e, 0x56, 0xa5,
    0xdf, 0x40, 0xd5, 0x32, 0x7f, 0x9a, 0xf4, 0x4e,
    0xc9, 0x09, 0x5e, 0x44, 0x61, 0xa3, 0x0e, 0xd1,
    0xa7, 0x8f, 0x78, 0x00, 0x98, 0xc4, 0xc2, 0xc2,
    0x75, 0x6e, 0x49, 0xc9, 0x9b, 0xba, 0x55, 0xc5,
    0x0b, 0x79, 0xaf, 0x5c, 0x1b, 0x23, 0xe1, 0xcf,
    0x4d, 0x0e, 0x4f, 0xe2, 0x56, 0x4f, 0x4b, 0x43,
    0x69, 0x24, 0x85, 0x0b, 0x04, 0x4a, 0xa1, 0x54,
    0x79, 0xcc, 0x8f, 0x1d, 0x1f, 0x98, 0x7d, 0xd7,
    0x65, 0x2a, 0x0e, 0x46, 0x56, 0x17, 0xe7, 0xf1,
    0xd5, 0xea, 0x77, 0x2c, 0x09, 0x96, 0xf0, 0x44,
    0xef, 0xee, 0x37, 0xf1, 0xcd, 0xe5, 0xf5, 0x06,
    0xbb, 0x4b, 0x6f, 0x72, 0x36, 0xb9, 0x79, 0x17,
    0xbd, 0xb9, 0x79, 0x37, 0x9f, 0x8c, 0x4e, 0x12,
    0x79, 0xb4, 0x80, 0xa3, 0xe5, 0xe8, 0xc8, 0x97,
    0x27, 0x50, 0xc9, 0xc2, 0x5f, 0x9e, 0x7b, 0x06,
    0xe6, 0x21, 0x09, 0xae, 0x80, 0xe0, 0x6a, 0x0e,
    0x7f, 0xc2, 0xf1, 0x29, 0x11, 0x9d, 0x01, 0x66,
    0x08, 0x7f, 0x82, 0xd1, 0xb1, 0x22, 0x8c, 0xc7,
    0x1e, 0x9e, 0x7b, 0x63, 0x80, 0xe0, 0x00, 0xfd,
    0x7c, 0x75, 0x8d, 0x00, 0xef, 0x6f, 0xd7, 0xbf,
    0xdd, 0xaf, 0xaf, 0xcf, 0xff, 0x85, 0x15, 0xb6,
    0xfc, 0x0f, 0x8e, 0x3e, 0x7f, 0x39, 0xff, 0x24,
    0x4f, 0xb0, 0x56, 0xd2, 0xbb, 0x57, 0xe7, 0xf7,
    0x40, 0x44, 0x74, 0x65, 0xe0, 0x6f, 0xbd, 0x69,
    0xf0, 0xcc, 0x81, 0xc8, 0xcd, 0xd7, 0x2b, 0x52,
    0x90, 0x8f, 0x19, 0xf1, 0x76, 0x7d, 0xbe, 0xbe,
    0xfc, 0xe7, 0x3a, 0xfe, 0x7a, 0x79, 0x7d, 0xf1,
    0xe5, 0x2b, 0x5a, 0x9a, 0x8f, 0x9b, 0x9b, 0xf5,
    0x2d, 0x6c, 0x4a, 0x4e, 0xe0, 0x52, 0x29, 0x26,
    0x94, 0xe0, 0xf0, 0x97, 0x0f, 0x14, 0x36, 0x77,
    0xab, 0xbb, 0x4d, 0xbc, 0xb9, 0xbf, 0xda, 0xfc,
    0x16, 0xbf, 0x5b, 0x6d, 0xd6, 0x48, 0x2a, 0xc2,
    0xed, 0xf5, 0xcd, 0xcd, 0xfa, 0x36, 0x7e, 0xf7,
    0xe5, 0xee, 0x63, 0xbc, 0xbe, 0xf8, 0x00, 0xfb,
    0xde, 0x77, 0x2c, 0x93, 0x7b, 0x28, 0xdc, 0x65,
    0x6b, 0x29, 0x27, 0x57, 0x6e, 0x53, 0x8d, 0x6b,
    0xd0, 0xb1, 0x2c, 0xcf, 0x40, 0xe2, 0xc9, 0xd9,
    0xf4, 0x3b, 0x95, 0x79, 0x00, 0xa4, 0xce, 0x40,
    0xc7, 0x54, 0xa3, 0xa2, 0x3a, 0xa9, 0x9c, 0x04,
    0xcd, 0xf9, 0x00, 0x37, 0xe8, 0xc6, 0x11, 0xfa,
    0xf3, 0xe5, 0xc6, 0xbf, 0xf8, 0x2a, 0xe1, 0xe1,
    0x33, 0xb8, 0xf8, 0x48, 0x0c, 0x80, 0x8f, 0x6b,
    0xc3, 0xb8, 0x5b, 0x5f, 0x01, 0x87, 0xab, 0xbb,
    0xfb, 0x5b, 0xc9, 0x34, 0x04, 0x9b, 0x9b, 0xd5,
    0x74, 0x72, 0xf6, 0xef, 0xe9, 0x1b, 0x2f, 0xfa,
    0x0f, 0x2c, 0xde, 0xe1, 0x02, 0xe2, 0x23, 0xad,
    0xce, 0x71, 0x15, 0xf8, 0x6a, 0x75, 0x81, 0xab,
    0xd9, 0x42, 0xad, 0xd6, 0xb8, 0x82, 0xa2, 0x94,
    0x56, 0xef, 0x71, 0xb5, 0xd0, 0x54, 0x3e, 0xe0,
    0x6a, 0x29, 0xa9, 0x7c, 0x1f, 0x04, 0x45, 0xc5,
    0x67, 0xe2, 0x05, 0x41, 0x20, 0xd9, 0x4c, 0x44,
    0x38, 0x9d, 0xcd, 0x33, 0x29, 0x58, 0x57, 0xf0,
    0x70, 0xea, 0xf9, 0x0f, 0x24, 0x9c, 0x8a, 0x78,
    0x08, 0x4e, 0x86, 0x46, 0x1a, 0x42, 0x25, 0xf8,
    0xf2, 0xcb, 0x97, 0x04, 0xc8, 0x4c, 0xd0, 0x03,
    0x30, 0xe3, 0xe6, 0xe8, 0x99, 0x2d, 0xf4, 0x60,
    0xb2, 0xab, 0x90, 0x22, 0x33, 0xe9, 0x33, 0x5b,
    0x2a, 0xaa, 0x68, 0x28, 0xb4, 0x2a, 0xe4, 0x1c,
    0x8d, 0xe9, 0xfe, 0x24, 0xa3, 0x3c, 0xb2, 0xaa,
    0x6a, 0x4c, 0xca, 0x0c, 0xde, 0x9b, 0x55, 0x10,
    0x0f, 0x59, 0x22, 0x44, 0xbe, 0xab, 0x78, 0x06,
    0x55, 0x71, 0x2e, 0xd8, 0xe5, 0x05, 0x45, 0xb3,
    0xf3, 0xa4, 0x82, 0xe3, 0x8e, 0x41, 0xa8, 0x60,
    0x18, 0x6e, 0x19, 0x64, 0x08, 0x4a, 0x0b, 0x4c,
    0x7a, 0x3c, 0x7b, 0xda, 0xe7, 0xf0, 0x4d, 0x9e,
    0x2b, 0x58, 0x03, 0xb1, 0x07, 0x18, 0xa2, 0x7c,
    0x06, 0xb8, 0x7f, 0xeb, 0x30, 0x27, 0x32, 0xa4,
    0x9c, 0x14, 0x40, 0x39, 0xe9, 0x18, 0x10, 0x4f,
    0x14, 0x4b, 0x34, 0x56, 0xa0, 0xf6, 0x4a, 0x01,
    0x4b, 0x26, 0xd0, 0xeb, 0xa9, 0x09, 0xa4, 0x5d,
    0x99, 0x3e, 0x65, 0xf5, 0x01, 0xd7, 0xf1, 0x8a,
    0xe9, 0xce, 0xdb, 0xe0, 0x83, 0x8e, 0xce, 0x69,
    0x5a, 0xca, 0x9a, 0xa4, 0x15, 0x70, 0x24, 0xab,
    0x75, 0xd9, 0x4c, 0xe9, 0x83, 0x96, 0x43, 0x16,
    0x17, 0x9d, 0x9c, 0x99, 0xbe, 0x4f, 0x80, 0x69,
    0x90, 0xb4, 0x66, 0x32, 0x58, 0xe2, 0x28, 0x0a,
    0xbb, 0x0f, 0x2a, 0xc6, 0x3f, 0xfe, 0x8e, 0xf5,
    0x22, 0x8e, 0xb4, 0xfe, 0xa1, 0x46, 0x5a, 0x03,
    0xad, 0x32, 0xef, 0x64, 0x46, 0x73, 0xd2, 0x4b,
    0xff, 0x9c, 0x5d, 0xaf, 0xce, 0x3f, 0x51, 0xb5,
    0xaa, 0x57, 0x74, 0x35, 0x83, 0xce, 0x95, 0x0a,
    0x57, 0x54, 0x38, 0xba, 0x1e, 0x9e, 0x83, 0x2b,
    0xdd, 0xde, 0x69, 0x9c, 0xa9, 0xbb, 0x77, 0xbb,
    0x5e, 0x5d, 0xa8, 0x03, 0x0c, 0x97, 0x78, 0x70,
    0x47, 0x91, 0x99, 0x22, 0xf1, 0x25, 0xd5, 0x3d,
    0x0c, 0xdc, 0x99, 0x29, 0xae, 0x68, 0x18, 0xa1,
    0x0f, 0xf4, 0x24, 0xd3, 0x0e, 0x64, 0xa9, 0x2e,
    0xa1, 0x24, 0xab, 0xa1, 0xd4, 0x4c, 0x59, 0x36,
    0x9d, 0x76, 0x0f, 0xc0, 0x50, 0x6f, 0x49, 0xc9,
    0x81, 0x5f, 0x1a, 0x47, 0xe8, 0xc3, 0xb2, 0x7e,
    0xe4, 0x5a, 0x75, 0x0c, 0x27, 0x56, 0x18, 0x81,
    0xed, 0xb1, 0x99, 0x6f, 0x99, 0x89, 0x16, 0xf5,
    0x8e, 0x07, 0xe7, 0xaa, 0x0b, 0x32, 0xf7, 0x07,
    0x8e, 0x4c, 0xf0, 0xda, 0x8c, 0x9c, 0x05, 0x07,
    0x04, 0x7a, 0x17, 0x07, 0x51, 0xd2, 0x25, 0x30,
    0x5d, 0xba, 0x9b, 0x3a, 0xf8, 0xfb, 0xc3, 0x7d,
    0x55, 0xc1, 0x62, 0x88, 0x50, 0xd4, 0x66, 0x8e,
    0x1c, 0x83, 0x02, 0xd4, 0x85, 0x81, 0x97, 0xbb,
    0x4a, 0x9e, 0xf1, 0x75, 0x17, 0x5a, 0x87, 0x54,
    0x64, 0x5c, 0x41, 0x2f, 0x9a, 0xc0, 0x73, 0xe3,
    0x43, 0x82, 0x7b, 0x28, 0x83, 0xc2, 0x83, 0x5c,
    0x08, 0x30, 0x1e, 0x01, 0x2d, 0x4b, 0xd6, 0x17,
    0x38, 0x02, 0x01, 0x64, 0xac, 0xae, 0x98, 0x4a,
    0x5c, 0xd2, 0x5c, 0xf8, 0x23, 0x47, 0xe5, 0x63,
    0x61, 0xf5, 0x63, 0x84, 0x7d, 0xd2, 0x66, 0xd2,
    0xa3, 0x14, 0x34, 0x4e, 0xb8, 0xae, 0x50, 0xe3,
    0xb2, 0xe0, 0x64, 0xf0, 0xd5, 0x6e, 0x8b, 0xfa,
    0x89, 0x2a, 0xd6, 0x6b, 0x70, 0xc3, 0x84, 0x91,
    0x38, 0xe8, 0xea, 0x32, 0xd0, 0xe1, 0xd0, 0xc6,
    0x3d, 0x40, 0xfb, 0x90, 0x07, 0xd1, 0xe8, 0x20,
    0xaf, 0x1a, 0xaa, 0xeb, 0x68, 0xa8, 0x2d, 0x8f,
    0x2a, 0xe4, 0xd4, 0x6c, 0x63, 0x61, 0x80, 0xe8,
    0xda, 0x3b, 0x9b, 0xb6, 0xde, 0x81, 0x4d, 0x94,
    0xc0, 0x7a, 0x82, 0xb2, 0x6d, 0xa1, 0x30, 0x02,
    0x2e, 0x41, 0xd7, 0x1c, 0x6d, 0x1a, 0x67, 0x09,
    0xb7, 0x5c, 0x09, 0x85, 0xce, 0x04, 0xe6, 0xda,
    0xc2, 0x35, 0xa8, 0x6a, 0xb0, 0x26, 0xf4, 0x34,
    0xec, 0x83, 0x37, 0x06, 0xe0, 0x40, 0x3b, 0xec,
    0x29, 0x2f, 0x0a, 0xa8, 0x17, 0x52, 0xa0, 0x37,
    0x98, 0x49, 0x52, 0x05, 0x64, 0x31, 0x8d, 0x86,
    0x7e, 0x82, 0x81, 0x43, 0xfd, 0x0d, 0x44, 0x09,
    0x7a, 0x43, 0xc9, 0x00, 0x42, 0xe4, 0x65, 0x5f,
    0xea, 0x3d, 0xed, 0x0f, 0xa0, 0xcb, 0x8d, 0x9e,
    0x3b, 0xca, 0x1f, 0x27, 0x80, 0x98, 0x8c, 0x2b,
    0x32, 0xd0, 0xb9, 0xbf, 0x53, 0x6c, 0x54, 0xa0,
    0xe9, 0xea, 0x9a, 0x6d, 0x13, 0x29, 0x1d, 0x49,
    0x86, 0x03, 0x9f, 0x3b, 0xd7, 0xa4, 0x50, 0x65,
    0x00, 0x28, 0x27, 0xad, 0x34, 0x9f, 0xb8, 0x93,
    0xfa, 0x40, 0x4c, 0x28, 0x95, 0x04, 0x97, 0x03,
    0xac, 0xfb, 0x4a, 0xf4, 0x0d, 0x96, 0x4b, 0x9c,
    0x82, 0x0e, 0xd9, 0x37, 0xd8, 0x94, 0xfc, 0x7d,
    0x07, 0xd2, 0x5b, 0x5f, 0x7d, 0x03, 0x1a, 0x18,
    0x9c, 0x68, 0xfc, 0xef, 0xec, 0x0b, 0x7b, 0x80,
    0x08, 0xd2, 0xd8, 0x21, 0x7a, 0x09, 0x88, 0x35,
    0xe8, 0x9f, 0x50, 0x73, 0x09, 0x96, 0x0a, 0xf5,
    0xc2, 0xfe, 0x1b, 0x99, 0x78, 0xd1, 0xc6, 0xe5,
    0x45, 0xbd, 0xbd, 0x58, 0xff, 0x28, 0xa4, 0x4f,
    0xc9, 0x41, 0x68, 0x06, 0x6c, 0x76, 0xd1, 0xcf,
    0x86, 0x38, 0x76, 0xb2, 0x4a, 0xd1, 0xb8, 0xae,
    0x0a, 0x08, 0xe0, 0x8f, 0xc0, 0x52, 0xf2, 0x50,
    0xe8, 0xb8, 0x6c, 0x74, 0x47, 0xe3, 0x23, 0xd6,
    0xe9, 0x10, 0x86, 0xb9, 0x17, 0xab, 0xee, 0x82,
    0x8d, 0x2e, 0x85, 0x7d, 0xf9, 0x93, 0x96, 0x49,
    0x09, 0xea, 0x87, 0xae, 0x8c, 0xc6, 0x89, 0x02,
    0x67, 0x3c, 0x18, 0x81, 0xc9, 0xba, 0x52, 0x38,
    0x96, 0xdc, 0x98, 0x6a, 0x57, 0x06, 0x1e, 0xa9,
    0xe5, 0x22, 0x69, 0x31, 0xe5, 0x05, 0xc7, 0xeb,
    0x48, 0x7c, 0x5a, 0x72, 0x04, 0x1c, 0x1b, 0xab,
    0xcc, 0x41, 0x6e, 0x86, 0xd5, 0x33, 0x64, 0xd4,
    0x83, 0xd1, 0x2a, 0xa6, 0x54, 0xa8, 0x9c, 0x02,
    0x6f, 0x11, 0x86, 0x32, 0xfb, 0xaa, 0x45, 0x24,
    0xb3, 0x33, 0x2d, 0xa2, 0x50, 0xda, 0x09, 0x2c,
    0xa2, 0x68, 0x0e, 0xdf, 0xc1, 0x77, 0x59, 0xa9,
    0xa4, 0xf0, 0x2e, 0x80, 0x3f, 0xf9, 0x70, 0x7d,
    0xcf, 0x3e, 0xdc, 0x7c, 0x7e, 0xc4, 0x6a, 0x0e,
    0xd4, 0xd6, 0x40, 0x70, 0xe1, 0xf4, 0x7b, 0x9e,
    0x1e, 0xac, 0x0c, 0x66, 0x04, 0x32, 0x28, 0xc4,
    0xc7, 0x9a, 0xd0, 0x13, 0x8c, 0xc9, 0xfa, 0x77,
    0xb9, 0x01, 0x4a, 0xe2, 0x8c, 0x4d, 0x98, 0x3c,
    0xa1, 0x26, 0xe3, 0x04, 0x33, 0xb0, 0x19, 0x3a,
    0x32, 0xf5, 0xd5, 0xf7, 0x88, 0x75, 0x0a, 0xfd,
    0x80, 0xda, 0xc0, 0xd4, 0x8f, 0x5b, 0x78, 0x07,
    0x26, 0x5c, 0x6a, 0x4f, 0x6d, 0x17, 0x70, 0x12,
    0x98, 0x9f, 0xdd, 0x18, 0x16, 0x60, 0xf2, 0x4b,
    0x36, 0x0a, 0x72, 0xbc, 0x89, 0x7b, 0xfa, 0xd5,
    0x65, 0xf7, 0x05, 0x21, 0x2b, 0x36, 0xfd, 0x30,
    0x72, 0x21, 0xe7, 0xe5, 0x32, 0x11, 0xfe, 0x4c,
    0x54, 0x85, 0xa2, 0x3e, 0x62, 0xe7, 0x7e, 0xf4,
    0x02, 0x3d, 0x54, 0x16, 0xe0, 0x5c, 0x66, 0x46,
    0x7c, 0x82, 0xf1, 0x5f, 0x0f, 0x65, 0x07, 0xa4,
    0xf7, 0x75, 0x09, 0x41, 0xf6, 0xf0, 0x12, 0x77,
    0xe6, 0x8b, 0xf8, 0xa1, 0x1d, 0x86, 0xc6, 0xfa,
    0x75, 0x9c, 0x61, 0x8a, 0x5c, 0x6b, 0x65, 0x7a,
    0x76, 0xe0, 0xe8, 0xc0, 0x9a, 0xc9, 0x23, 0x35,
    0x77, 0xa7, 0x08, 0x8b, 0xe5, 0xab, 0x55, 0x0a,
    0x1b, 0x17, 0x6a, 0xa4, 0x97, 0xe5, 0xcc, 0x0e,
    0x28, 0x0f, 0x46, 0x45, 0x8e, 0x00, 0x7a, 0x0c,
    0xe9, 0x2a, 0x64, 0xe6, 0x0c, 0x17, 0x95, 0x4e,
    0x74, 0xdf, 0xdc, 0xa7, 0xa9, 0x9c, 0xa0, 0xa2,
    0x78, 0xd8, 0x12, 0x02, 0x9b, 0xee, 0x80, 0xfe,
    0x04, 0x2b, 0x09, 0x8a, 0x19, 0x50, 0x6d, 0x42,
    0x3f, 0xec, 0xf6, 0xa7, 0x02, 0x93, 0x7c, 0x95,
    0xf2, 0xd1, 0x78, 0xf2, 0x04, 0x73, 0xb2, 0x8b,
    0x33, 0x98, 0x22, 0xd9, 0x89, 0x89, 0x9a, 0xf3,
    0xe8, 0x2e, 0x90, 0xa6, 0x0d, 0x2e, 0xc9, 0x87,
    0x5e, 0x26, 0x90, 0x8c, 0x66, 0x77, 0x50, 0xe7,
    0x41, 0xd8, 0x88, 0x75, 0x86, 0x13, 0xca, 0x5c,
    0xe4, 0x84, 0xc3, 0xc6, 0x66, 0x3d, 0x6c, 0x3c,
    0xae, 0xc3, 0xf0, 0xd8, 0x08, 0xe2, 0xe0, 0x25,
    0xdd, 0x31, 0x93, 0xfb, 0xa4, 0x5e, 0x38, 0xec,
    0xf9, 0xff, 0xd2, 0x04, 0x7c, 0x59, 0x75, 0xb7,
    0x9d, 0xac, 0x6f, 0x97, 0x01, 0xd5, 0xe0, 0xc2,
    0x9a, 0xae, 0xe8, 0x4b, 0xf5, 0x8f, 0xf8, 0x43,
    0xf9, 0x8e, 0x6f, 0xfb, 0xf8, 0x51, 0x93, 0x4f,
    0x83, 0xe0, 0x1c, 0xe9, 0x46, 0xa3, 0xd8, 0x33,
    0x7c, 0xd3, 0xa3, 0x21, 0xa1, 0xa7, 0x44, 0xa3,
    0x1e, 0x3a, 0xb2, 0xbd, 0xff, 0xa1, 0x0c, 0xd8,
    0xf5, 0x93, 0xbc, 0x4b, 0xb7, 0x9f, 0xb7, 0xc6,
    0x06, 0x81, 0x40, 0xb7, 0xe5, 0xc7, 0x07, 0xdf,
    0x8e, 0xed, 0x61, 0xda, 0xa3, 0x1f, 0x26, 0x18,
    0xfd, 0x16, 0xd8, 0x0f, 0x42, 0x05, 0xb6, 0x5f,
    0xea, 0xff, 0x8e, 0x80, 0xe0, 0xf7, 0x38, 0x3d,
    0xf5, 0xfc, 0xd3, 0xe9, 0x49, 0x10, 0x2e, 0x4e,
    0x76, 0xe9, 0x62, 0xc1, 0xf9, 0x62, 0xf6, 0xc0,
    0x27, 0xdf, 0xff, 0x07, 0xe4, 0x97, 0x0e, 0xbb,
};

// Identify size = 3096 (8536 uncompressed)
const uint32_t command_identify_size PROGMEM
    = ARRAY_SIZE(command_identify_data);
